services:
  - type: web
    name: webhook-rnmc
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python webhook_rnmc_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
